fail workflow on curl fail

diff --git a/.github/workflows/updateCanvasDispatch.yml b/.github/workflows/updateCanvasDispatch.yml
--- a/.github/workflows/updateCanvasDispatch.yml
+++ b/.github/workflows/updateCanvasDispatch.yml
@@ -44,4 +44,9 @@ jobs:
                   }
                 }
               ]
-          }'
+          }' --fail
+        
+        if [ $? -ne 0 ]; then
+            echo "Slack update failed!"
+            exit 1 
+        fi
